### ISSUE TITLE
Plans for gulp-jasmine2-phantomjs2

### ISSUE THREAD

**Issue by asiniy** [sandermak/gulp-jasmine2-phantomjs#11]
Hey!

Wonder to know, is there any plans for this plugin? The time is running out, that's why I think we need to go further.

**Comment by sandermak** [comment]
Hi!

I wrote this plugin out of a need for a current project. It fulfils my needs, so I have on immediate plans. Meanwhile, lots of similar projects have emerged. Check npm. If you have any specific issues/questions, feel free to open another issue.
